### PR TITLE
Modify mappend to avoid discarding

### LINKED ISSUE #2: Improve `Semigroup` instance
@chris-martin has done unmerged work on the `Semigroup` instance, see
- https://github.com/chrisdone/ini/pull/32
- https://github.com/chrisdone/ini/issues/31

@chris-martin : Do you want to port your PR to this repo?  Do you want to co-maintain `ini`?

### PR DESCRIPTION
**Pull request by chris-martin**
Closes #2

### CODE REVIEW

**Review by andreasabel — APPROVED** [review]

**Review by andreasabel — CHANGES_REQUESTED** [review]
Thanks!
Actually, would be good to add a test case for the new behavior.

**Comment by chris-martin** [comment]
Test case will be good, but I was hoping to do that in a separate step after first perhaps doing some cleanup in the existing test suite.

**Review by andreasabel — APPROVED** [review]
Ok, fine, thanks!

**Comment by andreasabel** [comment]
@chris-martin : I noticed this is still unreleased.  I would be easier to release this with a test case in place. Would you contribute a test case?

**Comment by chris-martin** [comment]
Sure, added to my to-do list.

**Pull request merged**
